"""
Phase 2 — Full Training Pipeline
==================================
Orchestrates end-to-end training:
  1. Load CSV dataset (generated by synthetic_generator.py)
  2. Add temporal lag/rolling features
  3. Per-queue LSTM training (volume forecaster)
  4. Per-queue XGBoost training (breach classifier) with LSTM embeddings
  5. Probability calibration on held-out test set
  6. SHAP explainer initialisation
  7. All metrics logged to MLflow
  8. Model artifacts saved to models/

Usage:
  python phase2_ml/train.py --data data/sample_data.csv
  python phase2_ml/train.py --data data/sample_data.csv --queues "Payment Processing"
"""

from __future__ import annotations

import argparse
import logging
import os
import pickle
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from dotenv import load_dotenv
from sklearn.model_selection import train_test_split

# Ensure project root is on path
sys.path.insert(0, str(Path(__file__).parents[1]))

from phase1_pipeline.feature_engineering import add_temporal_features, prepare_sequences
from phase1_pipeline.schemas import FeatureSnapshot
from phase2_ml.lstm_forecaster import LSTMForecaster, LSTMTrainer, LSTMInference
from phase2_ml.xgboost_classifier import XGBoostBreachClassifier, BreachEnsemble
from phase2_ml.calibration import CalibrationPipeline, calibration_report
from phase2_ml.shap_explainer import SHAPExplainer
from phase2_ml.mlflow_tracking import MLflowLogger

load_dotenv()
logging.basicConfig(
    level=os.getenv("LOG_LEVEL", "INFO"),
    format="%(asctime)s [%(levelname)s] %(name)s — %(message)s",
)
logger = logging.getLogger(__name__)

MODEL_DIR  = Path("models/")
MODEL_DIR.mkdir(parents=True, exist_ok=True)

QUEUE_NAMES = [
    "Document Review", "Compliance Check", "Payment Processing",
    "Customer Onboarding", "Risk Assessment", "Audit Preparation",
]

LSTM_PARAMS = {
    "input_size":   None,   # set after feature engineering
    "hidden_size":  int(os.getenv("LSTM_HIDDEN_SIZE",  "128")),
    "num_layers":   int(os.getenv("LSTM_NUM_LAYERS",   "2")),
    "dropout":      float(os.getenv("LSTM_DROPOUT",    "0.2")),
    "seq_len":      int(os.getenv("LSTM_SEQUENCE_LENGTH", "12")),
    "lr":           float(os.getenv("LSTM_LEARNING_RATE", "0.001")),
    "batch_size":   int(os.getenv("LSTM_BATCH_SIZE",   "32")),
    "epochs":       int(os.getenv("LSTM_EPOCHS",       "50")),
}


# ─────────────────────────────────────────────────────────────────────────────
# Step 1 — Data Loading
# ─────────────────────────────────────────────────────────────────────────────
def load_dataset(path: str) -> pd.DataFrame:
    logger.info(f"Loading dataset: {path}")
    df = pd.read_csv(path, parse_dates=["snapshot_time"])
    df = add_temporal_features(df)
    df = df.dropna(subset=["breach_label"])
    logger.info(f"Dataset: {len(df):,} rows | {df['queue_name'].nunique()} queues | breach_rate={df['breach_label'].mean():.3f}")
    return df


# ─────────────────────────────────────────────────────────────────────────────
# Step 2 — Per-Queue LSTM Training
# ─────────────────────────────────────────────────────────────────────────────
def train_lstm_for_queue(
    df: pd.DataFrame,
    queue_name: str,
    mlflow_logger: MLflowLogger,
) -> LSTMInference:
    """Train LSTM volume forecaster for one queue. Returns inference wrapper."""
    logger.info(f"\n{'='*60}\nTraining LSTM | queue={queue_name}\n{'='*60}")

    seq_len = LSTM_PARAMS["seq_len"]
    X, y_volume, timestamps = prepare_sequences(df, queue_name, seq_len=seq_len)

    if len(X) < 50:
        logger.warning(f"[{queue_name}] insufficient data ({len(X)} seq) — skipping LSTM")
        return None

    # For LSTM y → predict throughput at multiple steps ahead (1h=12, 2h=24, 4h=48 steps)
    # Here we use wip_count target as volume proxy
    q_df = df[df["queue_name"] == queue_name].reset_index(drop=True)

    # Build multi-horizon targets
    horizons = {"1h": 12, "2h": 24, "4h": 48}
    y_multi = np.zeros((len(X), 3))
    for j, (_, steps) in enumerate(horizons.items()):
        for i in range(len(X)):
            future_idx = i + seq_len + steps - 1
            if future_idx < len(q_df):
                y_multi[i, j] = q_df.iloc[future_idx].get("wip_count", 0.0)
            else:
                y_multi[i, j] = y_multi[i - 1, j] if i > 0 else 0.0

    split = int(len(X) * 0.8)
    X_tr, y_tr = X[:split],  y_multi[:split]
    X_val, y_val = X[split:], y_multi[split:]

    input_size = X_tr.shape[2]
    model   = LSTMForecaster(
        input_size  = input_size,
        hidden_size = LSTM_PARAMS["hidden_size"],
        num_layers  = LSTM_PARAMS["num_layers"],
        dropout     = LSTM_PARAMS["dropout"],
    )
    trainer = LSTMTrainer(
        model      = model,
        lr         = LSTM_PARAMS["lr"],
        epochs     = LSTM_PARAMS["epochs"],
        batch_size = LSTM_PARAMS["batch_size"],
        model_dir  = str(MODEL_DIR),
    )
    history = trainer.fit(X_tr, y_tr, X_val, y_val, queue_name=queue_name)

    # Log to MLflow
    mlflow_logger.log_lstm_training(
        queue_name = queue_name,
        params     = {**LSTM_PARAMS, "input_size": input_size},
        history    = history,
        model_path = str(MODEL_DIR / f"lstm_{queue_name.replace(' ', '_')}.pt"),
    )

    return LSTMInference(model=trainer.model)


# ─────────────────────────────────────────────────────────────────────────────
# Step 3 — Per-Queue XGBoost Training
# ─────────────────────────────────────────────────────────────────────────────
def train_xgboost_for_queue(
    df:           pd.DataFrame,
    queue_name:   str,
    lstm_model:   LSTMInference | None,
    mlflow_logger: MLflowLogger,
) -> BreachEnsemble:
    """Train all 3 XGBoost classifiers for one queue."""
    logger.info(f"\n{'='*60}\nTraining XGBoost ensemble | queue={queue_name}\n{'='*60}")

    q_df = df[df["queue_name"] == queue_name].copy().sort_values("snapshot_time")

    if len(q_df) < 200:
        logger.warning(f"[{queue_name}] insufficient data ({len(q_df)} rows) — skipping")
        return None

    # Inject LSTM forecasts into XGBoost features
    if lstm_model is not None:
        seq_len = LSTM_PARAMS["seq_len"]
        X_seqs, _, _ = prepare_sequences(df, queue_name, seq_len=seq_len)
        if len(X_seqs) > 0:
            forecasts = []
            for seq in X_seqs:
                pred = lstm_model.predict(seq)
                forecasts.append({
                    "lstm_forecast_1h": pred["mean"]["1h"],
                    "lstm_forecast_2h": pred["mean"]["2h"],
                    "lstm_forecast_4h": pred["mean"]["4h"],
                })
            # Align with q_df (sequences start at seq_len offset)
            pad = [{"lstm_forecast_1h": 0, "lstm_forecast_2h": 0, "lstm_forecast_4h": 0}] * seq_len
            all_forecasts = pad + forecasts
            for k in ["lstm_forecast_1h", "lstm_forecast_2h", "lstm_forecast_4h"]:
                q_df[k] = [f.get(k, 0.0) for f in all_forecasts[:len(q_df)]]
    else:
        q_df["lstm_forecast_1h"] = 0.0
        q_df["lstm_forecast_2h"] = 0.0
        q_df["lstm_forecast_4h"] = 0.0

    # Split: 70% train, 15% calibration, 15% test
    n = len(q_df)
    cal_start  = int(n * 0.70)
    test_start = int(n * 0.85)
    train_df   = q_df.iloc[:cal_start]
    cal_df     = q_df.iloc[cal_start:test_start]
    test_df    = q_df.iloc[test_start:]

    ensemble = BreachEnsemble()
    xgb_params = {
        "max_depth":        int(os.getenv("XGBOOST_MAX_DEPTH",       "6")),
        "n_estimators":     int(os.getenv("XGBOOST_N_ESTIMATORS",    "300")),
        "learning_rate":    float(os.getenv("XGBOOST_LEARNING_RATE", "0.05")),
        "subsample":        float(os.getenv("XGBOOST_SUBSAMPLE",     "0.8")),
    }

    calibrators: dict[int, CalibrationPipeline] = {}
    shap_explainers: dict[int, SHAPExplainer]   = {}

    for horizon in [1, 2, 4]:
        clf = ensemble.classifiers[horizon]
        clf.params.update(xgb_params)
        metrics = clf.fit_walk_forward(train_df, queue_name=queue_name)

        # Calibration on cal set
        X_cal, feat_names = clf._prepare_features(cal_df.copy())
        y_cal = cal_df["breach_label"].values.astype(int)

        if len(y_cal) > 20 and y_cal.sum() > 0:
            raw_proba = clf.model.predict_proba(X_cal)[:, 1]
            cal_pipe  = CalibrationPipeline(method="isotonic")
            cal_pipe.fit(raw_proba, y_cal)
            calibrators[horizon] = cal_pipe

            X_test, _ = clf._prepare_features(test_df.copy())
            y_test     = test_df["breach_label"].values.astype(int)
            if len(y_test) > 0 and y_test.sum() > 0:
                raw_test = clf.model.predict_proba(X_test)[:, 1]
                cal_test = cal_pipe.calibrate(raw_test)
                cal_rep  = calibration_report(y_test, raw_test, cal_test)
            else:
                cal_rep = {}
        else:
            cal_pipe = None
            cal_rep  = {}

        # SHAP
        try:
            shap_exp = SHAPExplainer(clf.model, feat_names)
            shap_explainers[horizon] = shap_exp
        except Exception as e:
            logger.warning(f"SHAP init failed: {e}")

        # MLflow
        mlflow_logger.log_xgboost_training(
            queue_name         = queue_name,
            horizon_hours      = horizon,
            params             = xgb_params,
            metrics            = metrics,
            model              = clf,
            feature_importance  = clf.get_feature_importance(),
            calibration_report  = cal_rep,
        )

        # Save calibrator
        safe = queue_name.replace(" ", "_")
        if cal_pipe:
            cal_pipe.save(str(MODEL_DIR / f"calibrator_{safe}_h{horizon}.pkl"))

        # Save SHAP
        if horizon in shap_explainers:
            with open(MODEL_DIR / f"shap_{safe}_h{horizon}.pkl", "wb") as f:
                pickle.dump(shap_explainers[horizon], f)

    ensemble.save_all(queue_name)
    logger.info(f"[{queue_name}] All models saved to {MODEL_DIR}")
    return ensemble


# ─────────────────────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────────────────────
def main():
    parser = argparse.ArgumentParser(description="Appian Training Pipeline")
    parser.add_argument("--data",   type=str, default="data/sample_data.csv")
    parser.add_argument("--queues", type=str, default=None,
                        help="Comma-separated queue names (default: all)")
    parser.add_argument("--skip-lstm", action="store_true", help="Skip LSTM training")
    args = parser.parse_args()

    df = load_dataset(args.data)
    queues = (
        [q.strip() for q in args.queues.split(",")]
        if args.queues
        else QUEUE_NAMES
    )
    logger.info(f"Training queues: {queues}")

    ml_logger = MLflowLogger()

    for queue_name in queues:
        if queue_name not in df["queue_name"].unique():
            logger.warning(f"Queue '{queue_name}' not found in dataset — skipping")
            continue

        # LSTM
        lstm_model = None
        if not args.skip_lstm:
            lstm_model = train_lstm_for_queue(df, queue_name, ml_logger)

        # XGBoost + Calibration + SHAP
        ensemble = train_xgboost_for_queue(df, queue_name, lstm_model, ml_logger)

    logger.info("\n" + "="*60 + "\n✓ All models trained and saved!\n" + "="*60)
    logger.info(f"  Model dir: {MODEL_DIR.absolute()}")
    logger.info(f"  MLflow:    {os.getenv('MLFLOW_TRACKING_URI', 'http://localhost:5000')}")


if __name__ == "__main__":
    main()
